"""Deterministically assemble the installable Quarto extension using only stdlib.

Module manifests own their resources. Generated bundles avoid Quarto flattening
script paths and introducing filename collisions between independent modules.
"""
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
CORE = [
    'core/registry.js', 'core/i18n.js', 'core/session.js', 'core/modes.js',
    'core/help.js', 'ui/frame.js', 'ui/viewport.js', 'ui/transitions.js',
    'ui/menu.js', 'ui/dock.js', 'ui/module.js',
]
STYLES = [
    'ui/frame.css', 'ui/content.css', 'ui/letterbox.css', 'ui/dock.css',
]


def resource(folder, name):
    path = (folder / name).resolve()
    if not path.is_relative_to(ROOT) or not path.is_file():
        raise ValueError(f'Invalid module resource: {name}')
    return path


def yaml(value, indent=0):
    """Serialize the JSON subset we use, including empty arrays and mappings."""
    pad = ' ' * indent
    if isinstance(value, dict):
        lines = []
        for key, item in value.items():
            if isinstance(item, (dict, list)) and item:
                lines.append(pad + str(key) + ':\n' + yaml(item, indent + 2))
            else:
                lines.append(pad + str(key) + ': ' + json.dumps(item, ensure_ascii=False))
        return '\n'.join(lines)
    return '\n'.join(
        pad + '- ' + (
            yaml(item, indent + 2).lstrip()
            if isinstance(item, (dict, list)) and item
            else json.dumps(item, ensure_ascii=False)
        )
        for item in value
    )


def merge_messages(target, source):
    for language, entries in source.items():
        messages = target.setdefault(language, {})
        for key, value in entries.items():
            if key in messages and messages[key] != value:
                raise ValueError(f'Conflicting translation: {key}')
            messages[key] = value


def assemble(check=False):
    scripts = [ROOT / path for path in CORE]
    styles = [ROOT / path for path in STYLES]
    messages = json.loads((ROOT / 'core/locales.json').read_text())
    config = json.loads((ROOT / 'core/format.json').read_text())
    format_config = config['contributes']['formats']['revealjs']
    plugins = []
    for manifest in sorted((ROOT / 'modules').glob('*/module.json')):
        module = json.loads(manifest.read_text())
        folder = manifest.parent
        if module['id'] != folder.name:
            raise ValueError(f'Module id must match its folder: {manifest}')
        if (folder / 'locales.json').exists():
            merge_messages(messages, json.loads((folder / 'locales.json').read_text()))
        scripts.extend(resource(folder, path) for path in module.get('scripts', []))
        styles.extend(resource(folder, path) for path in module.get('styles', []))
        format_config['filters'].extend(
            resource(folder, path).relative_to(ROOT).as_posix()
            for path in module.get('filters', [])
        )
        plugins.extend(module.get('plugins', []))

    scripts.append(ROOT / 'core/plugin.js')
    plugins.append({'name': 'RevealPresentation', 'script': ['runtime.js'], 'stylesheet': ['presentation.css']})
    names = [plugin['name'] for plugin in plugins]
    if len(names) != len(set(names)):
        raise ValueError('Duplicate Reveal plugin name.')
    format_config['revealjs-plugins'] = ['runtime/' + name for name in names]

    chunks = ['// Generated by core/build.py; edit the module sources.\n']
    for path in scripts:
        chunks.append('\n/* ' + path.relative_to(ROOT).as_posix() + ' */\n')
        if path.name == 'i18n.js':
            chunks.append('Presentation.messages=' + json.dumps(messages, ensure_ascii=False) + ';\n')
        chunks.append(path.read_text() + '\n;\n')
    outputs = {
        'runtime/RevealPresentation/runtime.js': ''.join(chunks),
        'runtime/RevealPresentation/presentation.css': '/* Generated by core/build.py; edit the module styles. */\n' + ''.join(
            '\n/* ' + path.relative_to(ROOT).as_posix() + ' */\n' + path.read_text()
            for path in styles
        ),
        '_extension.yml': '# Generated from core/format.json and modules/*/module.json.\n' + yaml(config) + '\n',
    }
    for plugin in plugins:
        directory = 'runtime/' + plugin['name'] + '/'
        if not plugin.get('script'):
            plugin = {**plugin, 'script': ['registration.js']}
            outputs[directory + 'registration.js'] = (
                '// Implementation is included in RevealPresentation/runtime.js.\n'
            )
        outputs[directory + 'plugin.yml'] = yaml(plugin) + '\n'

    for name, content in outputs.items():
        path = ROOT / name
        if check:
            if not path.exists() or path.read_text() != content:
                raise ValueError(f'Stale generated file: {name}')
        elif not path.exists() or path.read_text() != content:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    return list(outputs)


if __name__ == '__main__':
    assemble('--check' in sys.argv)
