// Completion markers and preview launchers. Runs only after successful render.
import { dirname, extname, fromFileUrl, join, toFileUrl } from "stdlib/path";
import {
  digest,
  envFiles,
  exists,
  inside,
  relative,
  resolve,
} from "./paths.ts";
const root = resolve(Deno.env.get("QUARTO_PROJECT_DIR") || Deno.cwd());
const output = resolve(Deno.env.get("QUARTO_PROJECT_OUTPUT_DIR") || root);
async function readObject(file: string): Promise<Record<string, any>> {
  try {
    return JSON.parse(await Deno.readTextFile(file));
  } catch (e) {
    if (e instanceof Deno.errors.NotFound || e instanceof SyntaxError) {
      return {};
    }
    throw e;
  }
}
const inputMarker = join(root, ".quarto/presentation/inputs.json");
const inputs = await readObject(inputMarker), changed: string[] = [];
const expected = JSON.parse(
  Deno.env.get("PRESENTATION_RENDER_EXPECTED") || "{}",
);
for (const [name, input] of Object.entries(inputs)) {
  if (!inside(root, name) || !await exists(name)) continue;
  const hash = await digest(await Deno.readFile(name));
  const verified = expected[name]
    ? hash === expected[name]
    : input.verified && hash === input.hash;
  if (!verified) changed.push(name);
}
// Consume the transaction before nested renders; new filters register new ones.
await Deno.writeTextFile(inputMarker, "{}");
if (changed.length) {
  const attempt = Number(Deno.env.get("PRESENTATION_RENDER_RETRY") || 0);
  if (attempt >= 3) {
    throw Error(
      "Presentation: source kept changing during rendering. Please save again after editing.",
    );
  }
  console.log("Presentation: verifying the current source before publishing.");
  for (const name of changed) {
    const status = await new Deno.Command("quarto", {
      args: ["render", name, "--quiet"],
      env: {
        PRESENTATION_RENDER_RETRY: String(attempt + 1),
        PRESENTATION_RENDER_EXPECTED: JSON.stringify({
          [name]: await digest(await Deno.readFile(name)),
        }),
      },
      stdin: "null",
      stdout: "inherit",
      stderr: "inherit",
    }).spawn().status;
    if (!status.success) Deno.exit(status.code);
  }
  Deno.exit(0);
}
const sourceMarker = join(root, ".quarto/presentation/sources.json");
const completed = await readObject(sourceMarker);
for (const [name, input] of Object.entries(inputs)) {
  completed[name] = input.metadata;
}
await Deno.writeTextFile(sourceMarker + ".tmp", JSON.stringify(completed));
await Deno.rename(sourceMarker + ".tmp", sourceMarker);
await Deno.mkdir(join(output, ".quarto/presentation"), { recursive: true });
const service =
  toFileUrl(join(dirname(fromFileUrl(import.meta.url)), "preview.ts")).href;
const launcher =
  `// Generated by Presentation.\nDeno.env.set('QUARTO_PROJECT_DIR',${
    JSON.stringify(root)
  });\nDeno.env.set('PRESENTATION_OUTPUT_DIR',${
    JSON.stringify(output)
  });\nawait import(${JSON.stringify(service)});\n`;
await Deno.writeTextFile(join(output, ".quarto/presentation/preview.ts"), launcher);
const marker = join(output, ".quarto/presentation/render.json"),
  revisions = await readObject(marker);
for (
  const name of await envFiles(
    "QUARTO_USE_FILE_FOR_PROJECT_OUTPUT_FILES",
    "QUARTO_PROJECT_OUTPUT_FILES",
  )
) {
  const page = resolve(name);
  if (extname(page) === ".html" && inside(output, page) && await exists(page)) {
    revisions[relative(output, page).replaceAll("\\", "/")] = crypto
      .randomUUID();
  }
}
const temporary = marker + ".tmp";
await Deno.writeTextFile(temporary, JSON.stringify(revisions));
await Deno.rename(temporary, marker);
