// Register the source during filtering. A generated project-local entry point
// avoids Quarto's unquoted absolute extension hook paths (spaces/namespaces).
import { dirname, fromFileUrl, join, toFileUrl } from "stdlib/path";
import { digest, exists, resolve } from "./paths.ts";
export async function prepareHooks(root:string) {
  const hooks =
    toFileUrl(join(dirname(fromFileUrl(import.meta.url)), "post_render.ts"))
      .href;
  const launcher =
    `// Generated by Presentation; uses Quarto's bundled runtime.\nimport ${
      JSON.stringify(hooks)
    };\n`;
  await Deno.mkdir(join(root, ".quarto/presentation"), { recursive: true });
  const target = join(root, ".quarto/presentation/hooks.ts");
  if (!await exists(target) || await Deno.readTextFile(target) !== launcher) {
    await Deno.writeTextFile(target, launcher);
  }
}
export async function register(
  root: string,
  source: string,
  pandocInput: string,
) {
  root = await Deno.realPath(resolve(root));
  source = await Deno.realPath(resolve(source));
  await prepareHooks(root);
  const marker = join(root, ".quarto/presentation/inputs.json");
  let inputs: Record<
    string,
    { hash: string; verified: boolean; metadata: string }
  > = {};
  try {
    inputs = JSON.parse(await Deno.readTextFile(marker));
  } catch (e) {
    if (!(e instanceof Deno.errors.NotFound || e instanceof SyntaxError)) {
      throw e;
    }
  }
  const bytes = await Deno.readFile(source);
  const sourceText = new TextDecoder().decode(bytes).replace(/^\uFEFF/, "")
    .replace(/\r\n/g, "\n");
  const frontMatter =
    sourceText.match(/^---[^\S\n]*\n[\s\S]*?\n(?:---|\.\.\.)[^\S\n]*(?:\n|$)/)
      ?.[0] || "";
  const body = sourceText.slice(frontMatter.length).trim();
  const metadata = await digest(new TextEncoder().encode(frontMatter));
  let completed: Record<string, string> = {};
  try {
    completed = JSON.parse(
      await Deno.readTextFile(join(root, ".quarto/presentation/sources.json")),
    );
  } catch (e) {
    if (!(e instanceof Deno.errors.NotFound || e instanceof SyntaxError)) {
      throw e;
    }
  }
  let rendered = pandocInput
    ? (await Deno.readTextFile(pandocInput)).replace(/\r\n/g, "\n")
    : "";
  const generated = rendered.lastIndexOf("::: {.quarto-auto-generated-content");
  if (generated >= 0) rendered = rendered.slice(0, generated);
  // A filter can run after the file changed. Compare the actual Pandoc input,
  // not merely two late reads of the QMD. Transformed/executed inputs use the
  // conservative verification pass below instead of assuming equivalence.
  inputs[source] = {
    hash: await digest(bytes),
    metadata,
    verified: rendered.trim() === body &&
      (!frontMatter || completed[source] === metadata),
  };
  await Deno.writeTextFile(marker, JSON.stringify(inputs));
}
if (import.meta.main) await register(Deno.args[0], Deno.args[1], Deno.args[2]);
